### ISSUE TITLE
Properties sort order not stable

### ISSUE THREAD

**Issue by cleanerx** [wuetherich/ds-annotation-builder#45]
Component properties in the generated xml files seem to get reordered every once in a while.
I receive updates from other developers that probably run a different java version.

**Comment by wuetherich** [comment]
You are right - I use a map in the implementation to store the properties ;-/

**Comment by wuetherich** [comment]
Fixed. You can install the latest development release (that contains this fix) from the following P2 repository:
http://www.wuetherich.com/ds-annotations-latest
