### ISSUE TITLE
Version not set to 1.1.0 if bind(Interface, Map) signature used

### ISSUE THREAD

**Issue by cleanerx** [wuetherich/ds-annotation-builder#46]
if the bind method with the Interface and service properties given as map is being used, the component version is set to 1.0.0.
Debugging into the SCRManager a version of 1.1.0 is required in order to find this bind signature.
If activate methods are added, the version is raised to 1.1.0 and SCR finds the defined method.

The annotation processor must set version 1.1.0 if this signature is being used.

**Comment by wuetherich** [comment]
Fixed. You can install the latest development release (that contains this fix) from the following P2 repository:
http://www.wuetherich.com/ds-annotations-latest
