### ISSUE TITLE
Using of lamba expressions in Java 8 corrupts building of xml-files

### ISSUE THREAD

**Issue by mikerumpf** [wuetherich/ds-annotation-builder#47]
Whenever using lambda expressions in java 8 in a Component-annotated class the building of the component xmls gets corrupted (for example delete an existing component xml and try rebuilding the xml).

Example-lambda: new ArrayList<String>().forEach(s -> System.out.print(s));

**Comment by mikerumpf** [comment]
typo in title

**Comment by wuetherich** [comment]
Fixed. You can install the latest development release (that contains this fix) from the following P2 repository:
http://www.wuetherich.com/ds-annotations-latest

I will provide a new official release in the next few days.
