### ISSUE TITLE
Update Site Domain down

### ISSUE THREAD

**Issue by SuperOok** [wuetherich/ds-annotation-builder#48]
It seems that the whole domain that also provides the update site is down, see   http://www.wuetherich.com/ds-annotations/update

The current error text on any page on whuetherich.com is

Die Domain ist aktuell nicht zu erreichen. Falls Sie Besucher dieser Seite sind, wenden Sie sich bitte an den Domaininhaber oder den Webmaster. 

Gründe für die nicht Erreichbarkeit der Domain künnen die folgenden sein: 

- es werden aktuell Wartungsarbeiten durchgeführt
- die Webseite wurde vorübergehend deaktiviert

Falls Sie der Inhaber dieser Seite sind, wenden Sie sich an ProfiHost

**Comment by wuetherich** [comment]
Fixed. The site was down for maintenance. Sorry for the inconvenience...
